Book_Shop.web/Controllers/DashboardController.cs
using Book_Shop.database;
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Book_Shop.web.Controllers
{
    public class DashboardController : Controller
    {
        DashboardServices services = new DashboardServices();

        private BookshopUserManager _userManager;
        private BookshopRoleManager _roleManager;

        public DashboardController()
        {
        }

        public DashboardController(BookshopUserManager userManager, BookshopRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = RoleManager;
        }

        public BookshopUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<BookshopUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public BookshopRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<BookshopRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        // GET: Dashboard
        public ActionResult Index()
        {
            DashboardViewModel model = new DashboardViewModel();
            model.UserCount = services.GetUserCount();
            model.Product = services.GetProductCount();
            model.Order = services.GetOrderCount();
            model.Neworder = services.GetNewOrderCount();
            model.InProgress = services.GetInProgressOrderCount();
            model.Delivered = services.GetDeliverdOrderCount();
            model.Category = services.GetCategoryCount();
            model.Contact = services.GetContactCount();

            return View(model);
        }

        public new ActionResult User()
        {
            return View();
        }

        public ActionResult UserTable(string roleID, string searchTerm, int? pageNo)
        {
            var pagesize = ConfigurationServices.Instance.CategoryPageSize();
            UserViewModel model = new UserViewModel();
            model.RoleID = roleID;
            model.SearchTerm = searchTerm;

            //model.Role = new List<IdentityRole>();
            // model.User = UserManager.Users.ToList();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var Users = UserManager.Users;
            if (!string.IsNullOrEmpty(searchTerm))
            {
                Users = Users.Where(x => x.Email.ToLower().Contains(searchTerm.ToLower()));
            }
            pageNo = pageNo ?? 1;
            var skipCount = (pageNo.Value - 1) * pagesize;
            model.User = Users.OrderBy(x => x.Email).Skip(skipCount).Take(pagesize).ToList();

          

            if (model.User != null)
            {
                model.pager = new Pager(Users.Count(), pageNo, pagesize);
                return PartialView(model);
            }
            else
            {
                return HttpNotFound();

            }
        }

        public async Task<ActionResult> UserDetails(string userID, bool isPartial = false)
        {
            UserDetailsViewModel model = new UserDetailsViewModel();
            var user = await UserManager.FindByIdAsync(userID);
            if (user != null)
            {
                model.User = user;
            }
            if (isPartial || Request.IsAjaxRequest())
            {
                return PartialView("_userdetails", model);
            }
            else
            {
                return View(model);
            }
        }
        public async Task<ActionResult> UserRoles(string userID)
        {
            UserRoleViewModel model = new UserRoleViewModel();

            model.AvailableRole = RoleManager.Roles.ToList();
            if (!string.IsNullOrEmpty(userID))
            {
                model.User = await UserManager.FindByIdAsync(userID);

                if (model.User != null)
                {
                    model.UserRole = model.User.Roles.Select(userRole => model.AvailableRole.FirstOrDefault(role => role.Id == userRole.RoleId)).ToList();
                }

            }
            return PartialView("_userRoles", model);

        }

        public async Task<ActionResult> AssignUserRole(string userID, string roleID)
        {

            if (!string.IsNullOrEmpty(userID) && !string.IsNullOrEmpty(roleID))
            {
                var user = await UserManager.FindByIdAsync(userID);

                if (user != null)
                {
                    var role = await RoleManager.FindByIdAsync(roleID);

                    if (role != null)
                    {
                        await UserManager.AddToRoleAsync(userID, role.Name);

                    }
                }

            }
            return RedirectToAction("userRoles", new { userID = userID });

        }

        public async Task<ActionResult> DeleteuserRole(string userID, string roleID)
        {

            if (!string.IsNullOrEmpty(userID) && !string.IsNullOrEmpty(roleID))
            {
                var user = await UserManager.FindByIdAsync(userID);

                if (user != null)
                {
                    var role = await RoleManager.FindByIdAsync(roleID);

                    if (role != null)
                    {
                        await UserManager.RemoveFromRoleAsync(userID, role.Name);

                    }
                }

            }
            return RedirectToAction("userRoles", new { userID = userID });

        }

        public ActionResult UserOrdersforAdmin(string userID, string status, int? pageNo)
        {
            UserOrdersViewModel model = new UserOrdersViewModel();
            model.UserID = userID;
            model.Status = status;



            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var pageSize = ConfigurationServices.Instance.CategoryPageSize();


            model.Order = OrderServices.Instance.SearchOrders(userID, status, pageNo.Value, pageSize);
            var totalRecord = OrderServices.Instance.SearchOrderscount(userID, status);
            model.Pager = new Pager(totalRecord, pageNo, pageSize);

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Deleteorder(int ID)
        {
            OrderServices.Instance.DeleteOrder(ID);
            return RedirectToAction("Userordersforadmin");
        }

        public ActionResult Role()
        {
            return View();
        }

      

        public ActionResult RoleTable(string roleID, string searchTerm, int? pageNo)
        {
            var pagesize = ConfigurationServices.Instance.CategoryPageSize();
            UserViewModel model = new UserViewModel();
            model.RoleID = roleID;
            model.SearchTerm = searchTerm;

            //model.Role = new List<IdentityRole>();
            // model.User = UserManager.Users.ToList();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var Users = UserManager.Users;
            if (!string.IsNullOrEmpty(searchTerm))
            {
                Users = Users.Where(x => x.Email.ToLower().Contains(searchTerm.ToLower()));
            }
            pageNo = pageNo ?? 1;
            var skipCount = (pageNo.Value - 1) * pagesize;
            model.User = Users.OrderBy(x => x.Email).Skip(skipCount).Take(pagesize).ToList();

            if (model.User != null)
            {
                model.pager = new Pager(Users.Count(), pageNo, pagesize);
                return PartialView(model);
            }
            else
            {
                return HttpNotFound();

            }
        }

        public ActionResult RoleDetails()
        {
            return View();
        }

        public  ActionResult UserRoleDetails(string userID)
        {
            UserRoleViewModel model = new UserRoleViewModel();

            model.AvailableRole = RoleManager.Roles.ToList();
            if (!string.IsNullOrEmpty(userID))
            {
                model.User =  UserManager.FindById(userID);

                if (model.User != null)
                {
                    model.UserRole = model.User.Roles.Select(userRole => model.AvailableRole.FirstOrDefault(role => role.Id == userRole.RoleId)).ToList();
                }

            }
            return PartialView(model);

        }

        public  ActionResult AssignRole(string userID, string roleID)
        {

            if (!string.IsNullOrEmpty(userID) && !string.IsNullOrEmpty(roleID))
            {
                var user = UserManager.FindById(userID);

                if (user != null)
                {
                    var role =  RoleManager.FindById(roleID);

                    if (role != null)
                    {
                         UserManager.AddToRole(userID, role.Name);

                    }
                }

            }
            return RedirectToAction("UserRoleDetails", new { userID = userID });

        }

        public ActionResult DeleteRole(string userID, string roleID)
        {

            if (!string.IsNullOrEmpty(userID) && !string.IsNullOrEmpty(roleID))
            {
                var user = UserManager.FindById(userID);

                if (user != null)
                {
                    var role = RoleManager.FindById(roleID);

                    if (role != null)
                    {
                        UserManager.RemoveFromRole(userID, role.Name);

                    }
                }

Book_Shop.web/Controllers/ProductController.cs
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class ProductController : Controller
    {
        //ProductServices productservices = new ProductServices();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string search, int? pageNo)
        {
            var pagesize = ConfigurationServices.Instance.ProductPageSize();
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var totalRecord = ProductServices.Instance.GetProductCount(search);
            model.Products = ProductServices.Instance.GetProductlist(search, pageNo.Value, pagesize);
            if (model.Products != null)
            {
                model.Pager = new Pager(totalRecord, pageNo, pagesize);
                return PartialView(model);
                //model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            else
            {
                return HttpNotFound();

            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            //CategoryServices categoryservices = new CategoryServices();
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoryServices.Instance.GetAllCategorieslist();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            //CategoryServices categoryservices = new CategoryServices();
            var newproduct = new Product();
            newproduct.Name = model.Name;
            newproduct.Description = model.Description;
            newproduct.OldPrice = model.OldPrice;
            newproduct.ISBNno = model.ISBNno;
            newproduct.Edition = model.Edition;
            newproduct.Author = model.Author;
            newproduct.Publisher = model.Publisher;
            newproduct.ProductStock = model.ProductStock;
            newproduct.Price = model.Price;
            newproduct.Category = CategoryServices.Instance.Getcategory(model.CategoryID);
            newproduct.ImageUrl = model.ImageUrl;
            ProductServices.Instance.CreateProduct(newproduct);
            return RedirectToAction("ProductTable");
        }

        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductServices.Instance.Getproduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.OldPrice = product.OldPrice;
            model.ISBNno = product.ISBNno;
            model.Edition = product.Edition;
            model.Author = product.Author;
            model.Publisher = product.Publisher;
            model.ProductStock = product.ProductStock;
            model.Price = product.Price;
            model.ImageUrl = product.ImageUrl;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.AvailableCategories = CategoryServices.Instance.GetAllCategorieslist();
            return PartialView(model);

        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {

            var existingproduct = ProductServices.Instance.Getproduct(model.ID);


            existingproduct.Name = model.Name;
            existingproduct.Description = model.Description;
            existingproduct.Price = model.Price;
            existingproduct.ISBNno = model.ISBNno;
            existingproduct.Author = model.Author;
            existingproduct.Publisher = model.Publisher;
            existingproduct.ProductStock = model.ProductStock;
            existingproduct.OldPrice = model.OldPrice;
            existingproduct.ImageUrl = model.ImageUrl;
            existingproduct.Category = null;
            existingproduct.CategoryID = model.CategoryID;
            ProductServices.Instance.UpdateProduct(existingproduct);
            return RedirectToAction("ProductTable");

        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductServices.Instance.DeleteProduct(ID);
            return RedirectToAction("producttable");
        }
        public ActionResult Details(int ID)
        {
            DetailProductViewModel model = new DetailProductViewModel();

            model.Products = ProductServices.Instance.Getproduct(ID);

            return View(model);

        }
    }
}

Book_Shop.web/Views/Dashboard/Role.cshtml
@{
    ViewBag.Title = "Role";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

<h2>Role</h2>
<div id="tablecontainer">

    @{
        Html.RenderAction("RoleTable");
    }

</div>

Book_Shop.web/Views/Dashboard/RoleDetails.cshtml
@{
    ViewBag.Title = "RoleDetails";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

<h2>Role</h2>
<div id="tablecontainer">

    @{
        Html.RenderAction("UserRoleDetails");
    }
    <b>  @Html.ActionLink("Go Back", "role", "dashboard")</b>

</div> 

Book_Shop.web/Views/Dashboard/RoleTable.cshtml
@model UserViewModel

@{
    ViewBag.Title = "RoleTable";
}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchtxt" name="search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="form-control btn btn-primary" type="button" id="searchBtn">Search</button>
                        </div>
                        @*<div class="col-md-4 pr-0">

                            <select class="form-control btn btn-primary" name="RoleID">
                                <option>Role</option>
                                @foreach (var role in Model.Role)
                                    {
                                        <option value="@role.Id">@role.Name</option>
                                    }
                            </select>
                        </div>*@
                        <div class="col-md-4 pr-0">
                            @*<button class="form-control btn btn-primary" type="button" id="resetBtn">Reset</button>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                @*<th class="font-weight-bold">ID</th>*@
                @*<th class="font-weight-bold">Name</th>*@
                <th class="font-weight-bold">User Name</th>
                <th class="font-weight-bold">Role</th>
                <th class="font-weight-bold">Email</th>
                <th class="font-weight-bold ">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.User != null && Model.User.Count > 0)
            {
                foreach (var user in Model.User)
                {
                    <tr>
                        @*<td>@user.Id</td>*@

                        @*<td>@user.Name</td>*@

                        <td>@user.UserName</td>
                      
                        <td>
                            @if (user.Roles != null)
                            {
                                <text>@user.Roles.Count </text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@user.Email</td>
                        <td>
                            <a href="@Url.Action("RoleDetails","dashboard", new { userID = user.Id})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

                        </td>

                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products found</td>
                </tr>
            }
        </tbody>
    </table>
    <div>

        @if (Model.pager != null && Model.pager.TotalPages > 1)
        {
            if (Model.pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.pager.StartPage; page <= Model.pager.EndPage; page++)
            {
                var activeclass = Model.pager.CurrentPage == page ? "Active bg-info" : string.Empty;
                <button class="@activeclass pageButtons" data-pageno="@page">@page</button>

            }

            if (Model.pager.CurrentPage < Model.pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.pager.EndPage">Last</button>
            }
        }
    </div>
</div>

<script>
     $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("Roletable", "dashboard")',
            data: {
                pageNo: $(this).attr("data-pageno"),
                searchTerm : "@Model.SearchTerm"
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#searchBtn").click(function () {
        var searchvalue = $("#searchtxt").val();

        $.ajax({
            url: '@Url.Action("RoleTable", "Dashboard")',
            data: {
                searchTerm : searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#resetBtn").click(function () {
        var searchvalue = '';

        $.ajax({
            url: '@Url.Action("RoleTable", "Dashboard")',
            data: {
                search : searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


</script>








     @*$("#newBtn").click(function () {


         $.ajax({
             url: '@Url.Action("Create","Product")',//"/product/Create",

         })
             .done(function (response) {
                 $("#actioncontainer").html(response);
                 focusAction("actioncontainer");
             })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                 alert("Fail");
             });

     });

     $(".editbtn").click(function () {

        $.ajax({
            url: '@Url.Action("Edit","Product")',//"/Product/Edit",
            data: {
                ID: $(this).attr("data-id")
            }
         })
             .done(function (response) {
                 $("#actioncontainer").html(response);
                 focusAction("actioncontainer");
             })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                 alert("Fail");
             });

     });


     $(".deletebtn").click(function () {

         var ConfirmDelete = confirm("Are you sure to delete this Record !");
         if (ConfirmDelete) {

                $.ajax({
                  type: "post",
                  url: '@Url.Action("Delete","Product")',//"/product/Delete",
                  data: {
                      ID: $(this).attr("data-id")
                  }
              })
                  .done(function (response) {
                      $("#tablecontainer").html(response);

                 })
                  .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                      alert("Fail");
                  });
         }
     });

    var products = [];
    $(".Addtocart").click(function () {
        var productID = $(this).attr("data-id");

        products.push(productID);

        $.cookie("CartProducts", products.join('-'), { path: '/' });
        alert("Add Product to cart");

    });*@

Book_Shop.web/Views/Dashboard/User.cshtml
@{
    ViewBag.Title = "User";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

<h2>User</h2>
<div id="tablecontainer">

    @{
        Html.RenderAction("UserTable");
    }

</div>

Book_Shop.web/Views/Dashboard/UserTable.cshtml
@model UserViewModel

@{
    ViewBag.Title = "UserTable";
}

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchtxt" name="search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="form-control btn btn-primary" type="button" id="searchBtn">Search</button>
                        </div>
                       @* <div class="col-md-4 pr-0">

    <select class="form-control btn btn-primary" name="RoleID">
         <option>Role</option>
         @foreach (var role in Model.Role)
         {
             <option value="@role.Id">@role.Name</option>
         }
     </select>
                        </div>*@
                        <div class="col-md-4 pr-0">
                            <button class="form-control btn btn-primary" type="button" id="resetBtn">Reset</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                @*<th class="font-weight-bold">ID</th>*@
                <th class="font-weight-bold">Name</th>
                <th class="font-weight-bold">User Name</th>
                <th class="font-weight-bold">Role</th>
                <th class="font-weight-bold">Email</th>
                <th class="font-weight-bold ">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.User != null && Model.User.Count > 0)
            {
                foreach (var user in Model.User)
                {
                    <tr>
                      
                       
                        <td>@user.Name</td>
                       
                        <td>@user.UserName</td>
                      
                        <td>
                            @if (user.Roles != null)
                            {
                                <text>@user.Roles.Count </text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@user.Email</td>
                        <td>
                            <a  href="@Url.Action("userdetails","dashboard", new { userID = user.Id})" >More Detail</a>
                         
                        </td>

                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products found</td>
                </tr>
            }
        </tbody>
    </table>
    <div>

        @if (Model.pager != null && Model.pager.TotalPages > 1)
        {
            if (Model.pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.pager.StartPage; page <= Model.pager.EndPage; page++)
            {
                var activeclass = Model.pager.CurrentPage == page ? "Active bg-info" : string.Empty;
                <button class="@activeclass pageButtons" data-pageno="@page">@page</button>

            }

            if (Model.pager.CurrentPage < Model.pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.pager.EndPage">Last</button>
            }
        }
    </div>
</div>

<script>
     $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("usertable", "dashboard")',
            data: {
                pageNo: $(this).attr("data-pageno"),
                searchTerm : "@Model.SearchTerm"
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#searchBtn").click(function () {
        var searchvalue = $("#searchtxt").val();

        $.ajax({
            url: '@Url.Action("UserTable", "Dashboard")',
            data: {
                searchTerm : searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#resetBtn").click(function () {
        var searchvalue = '';

        $.ajax({
            url: '@Url.Action("UserTable", "Dashboard")',
            data: {
                search : searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


     @*$("#newBtn").click(function () {


         $.ajax({
             url: '@Url.Action("Create","Product")',//"/product/Create",

         })
             .done(function (response) {
                 $("#actioncontainer").html(response);
                 focusAction("actioncontainer");
             })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                 alert("Fail");
             });

     });

     $(".editbtn").click(function () {

        $.ajax({
            url: '@Url.Action("Edit","Product")',//"/Product/Edit",
            data: {
                ID: $(this).attr("data-id")
            }
         })
             .done(function (response) {
                 $("#actioncontainer").html(response);
                 focusAction("actioncontainer");
             })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                 alert("Fail");
             });

     });


     $(".deletebtn").click(function () {

         var ConfirmDelete = confirm("Are you sure to delete this Record !");
         if (ConfirmDelete) {

                $.ajax({
                  type: "post",
                  url: '@Url.Action("Delete","Product")',//"/product/Delete",
                  data: {
                      ID: $(this).attr("data-id")
                  }
              })
                  .done(function (response) {
                      $("#tablecontainer").html(response);

                 })
                  .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                      alert("Fail");
                  });
         }
     });

    var products = [];
    $(".Addtocart").click(function () {
        var productID = $(this).attr("data-id");

        products.push(productID);

        $.cookie("CartProducts", products.join('-'), { path: '/' });
        alert("Add Product to cart");

    });*@

</script>