Book_Shop.web/Controllers/ProductController.cs
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class ProductController : Controller
    {
        //ProductServices productservices = new ProductServices();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string search, int? pageNo)
        {
            var pagesize = ConfigurationServices.Instance.ProductPageSize();
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var totalRecord = ProductServices.Instance.GetProductCount(search);
            model.Products = ProductServices.Instance.GetProductlist(search, pageNo.Value, pagesize);
            if (model.Products != null)
            {
                model.Pager = new Pager(totalRecord, pageNo, pagesize);
                return PartialView(model);
                //model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            else
            {
                return HttpNotFound();

            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            //CategoryServices categoryservices = new CategoryServices();
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoryServices.Instance.GetAllCategorieslist();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            //CategoryServices categoryservices = new CategoryServices();
            var newproduct = new Product();
            newproduct.Name = model.Name;
            newproduct.Description = model.Description;
            newproduct.OldPrice = model.OldPrice;
            newproduct.ISBNno = model.ISBNno;
            newproduct.Edition = model.Edition;
            newproduct.Author = model.Author;
            newproduct.Publisher = model.Publisher;
            newproduct.ProductStock = model.ProductStock;
            newproduct.Price = model.Price;
            newproduct.Category = CategoryServices.Instance.Getcategory(model.CategoryID);
            newproduct.ImageUrl = model.ImageUrl;
            ProductServices.Instance.CreateProduct(newproduct);
            return RedirectToAction("ProductTable");
        }

        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductServices.Instance.Getproduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.OldPrice = product.OldPrice;
            model.ISBNno = product.ISBNno;
            model.Edition = product.Edition;
            model.Author = product.Author;
            model.Publisher = product.Publisher;
            model.ProductStock = product.ProductStock;
            model.Price = product.Price;
            model.ImageUrl = product.ImageUrl;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.AvailableCategories = CategoryServices.Instance.GetAllCategorieslist();
            return PartialView(model);

        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {

            var existingproduct = ProductServices.Instance.Getproduct(model.ID);


            existingproduct.Name = model.Name;
            existingproduct.Description = model.Description;
            existingproduct.Price = model.Price;
            existingproduct.ISBNno = model.ISBNno;
            existingproduct.Author = model.Author;
            existingproduct.Publisher = model.Publisher;
            existingproduct.ProductStock = model.ProductStock;
            existingproduct.OldPrice = model.OldPrice;
            existingproduct.ImageUrl = model.ImageUrl;
            existingproduct.Category = null;
            existingproduct.CategoryID = model.CategoryID;
            ProductServices.Instance.UpdateProduct(existingproduct);
            return RedirectToAction("ProductTable");

        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductServices.Instance.DeleteProduct(ID);
            return RedirectToAction("producttable");
        }
        public ActionResult Details(int ID)
        {
            DetailProductViewModel model = new DetailProductViewModel();

            model.Products = ProductServices.Instance.Getproduct(ID);

            return View(model);

        }
    }
}

Book_Shop.web/Controllers/ShareController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class ShareController : Controller
    {
        public JsonResult UploadImage()
        {

            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);
                file.SaveAs(path);
                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }

        public ActionResult Aboutus()
        {
            return View();
        }
    }
}

Book_Shop.web/Views/Product/Create.cshtml
@model NewProductViewModel
@{
    ViewBag.Title = "Create";
    var imageurl = "/Content/images/placeholder-image.png";
}



<h2>Create Product</h2>

<form id="Createproduct">
    <div class="row">
        <div class="col-md-8">

            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        <option value="@category.ID">@category.Name</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" placeholder="Enter Name">
                @*@Html.ValidationMessageFor(m => m.Name, "", new {@class = "text-danger"})*@
            </div>

            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" placeholder="Enter Description">
                @*@Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })*@

            </div>

            <div class="form-group">
                <label>Author</label>
                <input class="form-control" name="Author" placeholder="Enter Author Name">
                @*@Html.ValidationMessageFor(m => m.Author, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label>Publisher</label>
                <input class="form-control" name="Publisher" placeholder="Enter Publisher Name">
                @*@Html.ValidationMessageFor(m => m.Publisher, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label>Old Price</label>
                <input class="form-control" name="OldPrice" placeholder="Enter Old Price">
                @*@Html.ValidationMessageFor(m => m.OldPrice, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" placeholder="Enter Price">
                @*@Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label>ISBN Number</label>
                <input class="form-control" name="ISBNno" placeholder="Enter ISBN Number">
                @*@Html.ValidationMessageFor(m => m.ISBNno, "", new { @class = "text-danger" })*@
            </div>


            <div class="form-group">
                <label>Edition</label>
                <input class="form-control" name="Edition" placeholder="Enter Edition">
                @*@Html.ValidationMessageFor(m => m.Edition, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label>Stock</label>
                <input class="form-control" name="ProductStock" placeholder="Enter Product Stock">
                @*@Html.ValidationMessageFor(m => m.ProductStock, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group">
                <label>Image</label>
                <input id="ImageUrl" name="ImageUrl" type="hidden" />
                <input class="form-control" id="Uploadimage" name="Image" type="file" accept=".png, .jpg" required />
                @*@Html.ValidationMessageFor(m => m.ImageUrl, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="col-md-4">
            <br />
            <br />
            <div class="thumb">
                <img src="@imageurl" id="productimage" style="height:300px;width:400px" />
            </div>
        </div>

        <div>
            <button id="savebtn" type="button" class="btn btn-primary">Save</button>
            <button id="cancelbtn" type="button" class="btn btn-primary">Cancel</button>
        </div>

    </div>
</form>



<style>
    .error {
        color: red;
    }
</style>

<script>


    $.validator.addMethod("alphabetsnspace", function (value, element) {
        return this.optional(element) || /^[a-zA-Z ]*$/.test(value);
    });
    jQuery.validator.setDefaults({
        debug: true,
        success: "valid"
    });

    //jQuery.validator.addMethod("accept", function (value, element, param) {
    //    return value.match(new RegExp("." + param + "$"));
    //});




    $("#Createproduct").validate({
        rules: {

            Name: {
                required: true,
                minlength: 3,
                alphabetsnspace : true,
                maxlength: 50,
            },

            Description: {
                required: true,
                minlength: 3,
                maxlength: 500,
            },

            Author: {
                required: true,
                alphabetsnspace : true,

            },

            Publisher: {
                required: true,
                alphabetsnspace : true,

            },

            OldPrice: {
                required: true,
                range: [1, 100000],
            },


            Price: {
                required: true,
                range: [1, 100000],
            },

            ISBNno: {
                required: true,
               
            },

            Edition: {
                required: true,
                maxlength: 20,
                number: true,
            },

            ProductStock: {
                required: true,
                number: true,
            },

            Image: {
                required: true,
            }


        },





        messages: {

            Name: {
                required: 'Name is Required',
                minlength: 'Minimam length is 3',
                alphabetsnspace:'Only Letters and Space is required!',
                maxlength: 'Maximan length is 50',
            },


            Description: {
                required: 'Description is required',
                minlength: 'minimam length is 3',
                maxlength: 'Maximan length is 500',
            },

            Author: {
                required: 'Author Name is required !!',
                alphabetsnspace: 'Only Letters and Space is required!',
            },

            Publisher: {
                required: 'Publisher Name is required !!',
                alphabetsnspace: 'Only Letters and Space is required!',
            },

            OldPrice: {
                required: 'Old Price is required',
                range: 'Old Price range should be between 1 - 100000 !!',
                
            },


            Price: {
                required: 'New Price is required',
                range: 'Price range should be between 1 - 100000 !!',
            },


            ISBNno: {
                required: 'ISBN number is required !!',
                

            },


            Edition: {
                required: 'Edition is required!',
                maxlength: 'Maximam length is 20!',
                number: 'Only Number is required!',

            },


            ProductStock: {
                required: 'Stock Product is required!',
                number: 'Only Number is required!',

            },


            Image: {
                required: 'File is required',
            }

        }
    })

    $("#savebtn").click(function () {
        if ($("#Createproduct").valid())
        {

        $.ajax({
            type: "Post",
            url: '@Url.Action("Create","Product")',//"/Product/Create",
            data: $("#Createproduct").serialize()
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
                $("#actioncontainer").html("");
                focusAction("tablecontainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
        }
        else {
            swal({
                title: "Warning",
                text: "Please Enter all required field !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
        }
    });


    $("#cancelbtn").click(function () {

        $("#actioncontainer").html("");
        focusAction("tablecontainer");
    });



   $("#Uploadimage").change(function () {
   debugger;
   var element = this;
   var formData = new FormData();
   var totalfiles = element.files.length;

   for (var i = 0; i < totalfiles; i++) {

       var file = element.files[i];
       formData.append("photo", file);
        }

        $.ajax({
            type: "Post",
            url: '@Url.Action("UploadImage","Share")',// "/Share/UploadImage/",
            datatype: "json",
            data: formData,
            contentType:false,
            processData:false
        })
            .done(function (response) {
                console.log(response);
                if (response.Success) {
                    $("#ImageUrl").val(response.ImageURL);
                    $("#productimage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });

    });

</script>

Book_Shop.web/Views/Product/Edit.cshtml
@model  EditProductViewModel
@{
    ViewBag.Title = "Edit";
    var imageurl = !string.IsNullOrEmpty(Model.ImageUrl) ? Model.ImageUrl : "/Content/images/placeholder-image.png";

}

<h2>Edit</h2>

<form id="editproduct">
    <div class="row">
        <div class="col-md-8">
            <input type="hidden" name="ID" value="@Model.ID" />

            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                        <option value="@category.ID" @selected> @category.Name</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>

            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>

            <div class="form-group">
                <label>Old Price</label>
                <input class="form-control" name="OldPrice" value="@Model.OldPrice" />
            </div>

            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" value="@Model.Price" />
            </div>

            <div class="form-group">
                <label>Author</label>
                <input class="form-control" name="Author" value="@Model.Author" />
            </div>

            <div class="form-group">
                <label>Publisher</label>
                <input class="form-control" name="Publisher" value="@Model.Publisher" />
            </div>

            <div class="form-group">
                <label>ISBN Number</label>
                <input class="form-control" name="ISBNno" value="@Model.ISBNno" />
            </div>
            <div class="form-group">
                <label>Edition</label>
                <input class="form-control" name="Edition" value="@Model.Edition" />
            </div>

            <div class="form-group">
                <label>Stock</label>
                <input class="form-control" name="ProductStock" value="@Model.ProductStock" />
            </div>

            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageUrl" name="imageUrl" value="@Model.ImageUrl" />
                <input id="Uploadimage" class="form-control" type="file" name="Image" accept=".png, .jpg" />
            </div>

        </div>
        <br />
        <br />
        <div class="col-md-4">
            <div class="thumb">
                <img src="@imageurl" id="productimage" style="height:300px;width:400px" />
            </div>
        </div>

        <div>
            <button id="UpdateBtn" type="button" class="btn btn-primary">Update</button>
            <button id="cancelbtn" type="button" class="btn btn-primary">Cancel</button>
        </div>
    </div>
</form>


<style>
    .error {
        color: red;
    }
</style>

<script>
    $.validator.addMethod("alphabetsnspace", function (value, element) {
        return this.optional(element) || /^[a-zA-Z ]*$/.test(value);
    });
    jQuery.validator.setDefaults({
        debug: true,
        success: "valid"
    });

    $("#editproduct").validate({
        rules: {

            Name: {
                required: true,
                minlength: 3,
                alphabetsnspace: true,
                maxlength: 50,
            },

            Description: {
                required: true,
                minlength: 3,
                maxlength: 500,
            },

            Author: {
                required: true,
                alphabetsnspace: true,

            },

            Publisher: {
                required: true,
                alphabetsnspace: true,

            },

            OldPrice: {
                required: true,
                range: [1, 100000],
            },


            Price: {
                required: true,
                range: [1, 100000],
            },

            ISBNno: {
                required: true,
                
            },

            Edition: {
                required: true,
                maxlength: 20,
                number: true,
            },

            ProductStock: {
                required: true,
                number: true,
            },

            Image: {
                required: true,
            }


        },





        messages: {

            Name:
            {
                required: 'Name is Required',
                minlength: 'Minimam length is 3',
                alphabetsnspace: 'Only Letters and Space is required!',
                maxlength: 'Maximan length is 50',
            },

            Description:
            {
                required: 'Description is required',
                minlength: 'minimam length is 3',
                maxlength: 'Maximan length is 500',
            },

            Author:
            {
                required: 'Author Name is required !!',
                alphabetsnspace: 'Only Letters and Space is required!',
            },

            Publisher:
            {
                required: 'Publisher Name is required !!',
                alphabetsnspace: 'Only Letters and Space is required!',
            },

            OldPrice:
            {
                required: 'Old Price is required',
                range: 'Old Price range should be between 1 - 100000 !!',
            },


            Price:
            {
                required: 'New Price is required',
                range: 'Price range should be between 1 - 100000 !!',
            },

            ISBNno:
            {
                required: 'ISBN number is required !!',
            },

            Edition:
            {
                required: 'Edition is required!',
                maxlength: 'Maximam length is 20!',
                number: 'Only Number is required!',
            },


            ProductStock:
            {
                required: 'Stock Product is required!',
                number: 'Only Number is required!',
            },


            Image:
            {
                required: 'File is required',
            }

        }
    })

    $("#UpdateBtn").click(function () {
        if ($("#editproduct").valid())
        {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Edit","Product")',//"/Product/Edit",
            data: $("#editproduct").serialize()
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
                $("#actioncontainer").html("");
                focusAction("tablecontainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
        }
        else {
            swal({
                title: "Warning",
                text: "Please Enter all required field !",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
        }
    });
     $("#cancelbtn").click(function () {

                $("#actioncontainer").html("");
                focusAction("tablecontainer");
    });

    ///
    $("#Uploadimage").change(function () {
        debugger;
        var element = this;
        var formData = new FormData();
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {

            var file = element.files[i];
            formData.append("photo", file);
        }

        $.ajax({
            type: "Post",
            url: '@Url.Action("UploadImage","Share")',// "/Share/UploadImage/",
            datatype: "json",
            data: formData,
            contentType:false,
            processData:false
        })
            .done(function (response) {
                console.log(response);
                if (response.Success) {
                    $("#ImageUrl").val(response.ImageURL);
                    $("#productimage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });

    });
</script>

Book_Shop.web/Views/Product/ProductTable.cshtml
@model ProductSearchViewModel

@{
    ViewBag.Title = "ProductTable";
}

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchtxt" name="search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="form-control btn btn-primary" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="form-control btn btn-primary" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="form-control btn btn-primary" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="font-weight-bold">Product Name</th>
                <th class="font-weight-bold">Category</th>
                <th class="font-weight-bold">Price</th>
                <th class="font-weight-bold ">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name </text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td>
                            <button class="editbtn" data-id="@product.ID"><i class="fas fa-edit " style="color:#0d48c2"></i></button>
                            <button class="deletebtn" data-id="@product.ID"><i class="fas fa-trash-alt" style="color:#0d48c2"></i></button>
                            @*<button class="Addtocart" data-id="@product.ID">Add To Cart</button>*@
                        </td>

                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products found</td>
                </tr>
            }
        </tbody>
    </table>
    <div>

        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {
            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                var activeclass = Model.Pager.CurrentPage == page ? "Active bg-info" : string.Empty;
                <button class="@activeclass pageButtons" data-pageno="@page">@page</button>

            }

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>
            }
        }
    </div>
</div>

<script>
     $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',
            data: {
                pageNo: $(this).attr("data-pageno"),
                search : "@Model.SearchTerm"
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#searchBtn").click(function () {
        var searchvalue = $("#searchtxt").val();

        $.ajax({
            url: '@Url.Action("producttable", "Product")',
            data: {
                search : searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#resetBtn").click(function () {
        var searchvalue = '';

        $.ajax({
            url: '@Url.Action("producttable", "Product")',
            data: {
                search : searchvalue
            }
        })
            .done(function (response) {
                $("#tablecontainer").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


     $("#newBtn").click(function () {


         $.ajax({
             url: '@Url.Action("Create","Product")',//"/product/Create",

         })
             .done(function (response) {
                 $("#actioncontainer").html(response);
                 focusAction("actioncontainer");
             })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                 alert("Fail");
             });

     });

     $(".editbtn").click(function () {

        $.ajax({
            url: '@Url.Action("Edit","Product")',//"/Product/Edit",
            data: {
                ID: $(this).attr("data-id")
            }
         })
             .done(function (response) {
                 $("#actioncontainer").html(response);
                 focusAction("actioncontainer");
             })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                 alert("Fail");
             });

     });


     $(".deletebtn").click(function () {

         var ConfirmDelete = confirm("Are you sure to delete this Record !");
         if (ConfirmDelete) {

                $.ajax({
                  type: "post",
                  url: '@Url.Action("Delete","Product")',//"/product/Delete",
                  data: {
                      ID: $(this).attr("data-id")
                  }
              })
                  .done(function (response) {
                      $("#tablecontainer").html(response);

                 })
                  .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                      alert("Fail");
                  });
         }
     });

    var products = [];
    $(".Addtocart").click(function () {
        var productID = $(this).attr("data-id");

        products.push(productID);

        $.cookie("CartProducts", products.join('-'), { path: '/' });
        alert("Add Product to cart");

    });

</script>