Book_Shop.web/Controllers/OrderController.cs
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class OrderController : Controller
    {
        private BookshopUserManager _userManager;
        private BookshopRoleManager _roleManager;

        public OrderController()
        {
        }

        public OrderController(BookshopUserManager userManager, BookshopRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = RoleManager;
        }

        public BookshopUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<BookshopUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public BookshopRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<BookshopRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        // GET: Order


        public ActionResult OrderView()
        {
            return View();
        }
        public ActionResult Index(string userID, string status, int? pageNo)
        {
            OrderViewModel model = new OrderViewModel();
            model.UserID = userID;
            model.Status = status;
         
            

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var pageSize = ConfigurationServices.Instance.CategoryPageSize();


            model.Order = OrderServices.Instance.SearchOrders(userID, status, pageNo.Value, pageSize);
            var totalRecord = OrderServices.Instance.SearchOrderscount(userID, status);
            //model.User = UserManager.Users.ToList();
            model.Pager = new Pager(totalRecord, pageNo, pageSize);

            return PartialView(model);
        }

        public ActionResult Details(int ID)
        {
            OrderDetailViewModel model = new OrderDetailViewModel();
            model.Order = OrderServices.Instance.GetOrderbyID(ID);
            if (model.Order != null)
            {
                model.Orderby = UserManager.FindById(model.Order.UserID);
            }
            model.AvailableStatuses = new List<string>() { "Pending", "In Progress", "Delivered" };

            return View(model);
        }

       
        public JsonResult ChangeStatus(string status, int ID)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            result.Data = new { Success = OrderServices.Instance.UpdateOrderStatus(ID, status) };
            return result;
        }

        [HttpPost]
        public ActionResult Deleteorder(int ID)
        {
            OrderServices.Instance.DeleteOrder(ID);
            return RedirectToAction("index");
        }
      
        public ActionResult LogedUser()
        {
            return View();
        }


        [Authorize]
        public ActionResult LogedInUser()
        {
            BookshopUser model = new BookshopUser();
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (user != null)
            {
                model.Id = user.Id;
                model.Name = user.Name;
                model.UserName = user.UserName;
                model.Email = user.Email;
                model.City = user.City;
                model.Address = user.Address;
                model.PhoneNumber = user.PhoneNumber;



            }
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult LogedInUser(BookshopUser user)
        {
            OrderServices.Instance.UpdateUser(user);
            return RedirectToAction("LogedInUser");
        }
    }
}

Book_Shop.web/Controllers/ProductController.cs
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class ProductController : Controller
    {
        //ProductServices productservices = new ProductServices();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string search, int? pageNo)
        {
            var pagesize = ConfigurationServices.Instance.ProductPageSize();
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var totalRecord = ProductServices.Instance.GetProductCount(search);
            model.Products = ProductServices.Instance.GetProductlist(search, pageNo.Value, pagesize);
            if (model.Products != null)
            {
                model.Pager = new Pager(totalRecord, pageNo, pagesize);
                return PartialView(model);
                //model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            else
            {
                return HttpNotFound();

            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            //CategoryServices categoryservices = new CategoryServices();
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoryServices.Instance.GetAllCategorieslist();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            //CategoryServices categoryservices = new CategoryServices();
            var newproduct = new Product();
            newproduct.Name = model.Name;
            newproduct.Description = model.Description;
            newproduct.OldPrice = model.OldPrice;
            newproduct.ISBNno = model.ISBNno;
            newproduct.Edition = model.Edition;
            newproduct.Author = model.Author;
            newproduct.Publisher = model.Publisher;
            newproduct.ProductStock = model.ProductStock;
            newproduct.Price = model.Price;
            newproduct.Category = CategoryServices.Instance.Getcategory(model.CategoryID);
            newproduct.ImageUrl = model.ImageUrl;
            ProductServices.Instance.CreateProduct(newproduct);
            return RedirectToAction("ProductTable");
        }

        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductServices.Instance.Getproduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.OldPrice = product.OldPrice;
            model.ISBNno = product.ISBNno;
            model.Edition = product.Edition;
            model.Author = product.Author;
            model.Publisher = product.Publisher;
            model.ProductStock = product.ProductStock;
            model.Price = product.Price;
            model.ImageUrl = product.ImageUrl;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.AvailableCategories = CategoryServices.Instance.GetAllCategorieslist();
            return PartialView(model);

        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {

            var existingproduct = ProductServices.Instance.Getproduct(model.ID);


            existingproduct.Name = model.Name;
            existingproduct.Description = model.Description;
            existingproduct.Price = model.Price;
            existingproduct.ISBNno = model.ISBNno;
            existingproduct.Author = model.Author;
            existingproduct.Publisher = model.Publisher;
            existingproduct.ProductStock = model.ProductStock;
            existingproduct.OldPrice = model.OldPrice;
            existingproduct.ImageUrl = model.ImageUrl;
            existingproduct.Category = null;
            existingproduct.CategoryID = model.CategoryID;
            ProductServices.Instance.UpdateProduct(existingproduct);
            return RedirectToAction("ProductTable");

        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductServices.Instance.DeleteProduct(ID);
            return RedirectToAction("producttable");
        }
        public ActionResult Details(int ID)
        {
            DetailProductViewModel model = new DetailProductViewModel();

            model.Products = ProductServices.Instance.Getproduct(ID);

            return View(model);

        }
    }
}

Book_Shop.web/Controllers/ShopController.cs
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class ShopController : Controller
    {
        private BookshopSignInManager _signInManager;
        private BookshopUserManager _userManager;
        public BookshopSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<BookshopSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public BookshopUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<BookshopUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximaumPrice, int? categoryID, int? sortby, int? pageNo)
        {
            ShopViewModel model = new ShopViewModel();
            var PageSize = ConfigurationServices.Instance.ShopPageSize();

            model.FeaturedCategories = CategoryServices.Instance.GetShopCategory();
            model.MaximamPrice = ProductServices.Instance.GetMaximumPrice();
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.searchTerm = searchTerm;
            model.sortby = sortby;
            model.categoryID = categoryID;
              
            var totalCounts = ProductServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximaumPrice, categoryID, sortby);
            model.Products = ProductServices.Instance.SearchProducts(searchTerm, minimumPrice, maximaumPrice, categoryID, sortby, pageNo.Value, PageSize);
            model.pager = new Pager(totalCounts, pageNo, PageSize);
            return View(model);
        }



        public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximaumPrice, int? categoryID, int? sortby, int? pageNo)
        {
            FilterProductsViewModel model = new FilterProductsViewModel();
            var PageSize = ConfigurationServices.Instance.ShopPageSize();
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.searchTerm = searchTerm;
            model.sortby = sortby;
            model.categoryID = categoryID;

            var totalCounts = ProductServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximaumPrice, categoryID, sortby);
            model.Products = ProductServices.Instance.SearchProducts(searchTerm, minimumPrice, maximaumPrice, categoryID, sortby, pageNo.Value, PageSize);
            model.pager = new Pager(totalCounts, pageNo, PageSize);
            return PartialView(model);
        }
        // GET: Shop
        [Authorize]
        public ActionResult Checkout()
        {
            CheckoutViewModel model = new CheckoutViewModel();
            var cartproductcookies = Request.Cookies["CartProducts"];
            if (cartproductcookies != null && !string.IsNullOrEmpty(cartproductcookies.Value))
            {
                model.CartproductIDs = cartproductcookies.Value.Split('-').Select(x => int.Parse(x)).ToList();
                model.Cartproducts = ProductServices.Instance.GetProductlist(model.CartproductIDs);
                model.User = UserManager.FindById(User.Identity.GetUserId());
            }
            return View(model);
        }
        public JsonResult PlaceOrder(string productIDs)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            if (!string.IsNullOrEmpty(productIDs))
            {
                var productQuantities = productIDs.Split('-').Select(x => int.Parse(x)).ToList();

                var BoughtProduct = ProductServices.Instance.GetProductlist(productQuantities.Distinct().ToList());

                Order neworder = new Order();
                neworder.UserID = User.Identity.GetUserId();
                neworder.OrderedAt = DateTime.Now;
                neworder.Status = "Pending";
                neworder.TotalAmount = BoughtProduct.Sum(x => x.Price * productQuantities.Where(productID => productID == x.ID).Count());

                neworder.OrderItem = new List<OrderItem>();
                neworder.OrderItem.AddRange(BoughtProduct.Select(x => new OrderItem() { ProductID = x.ID, Quantity = productQuantities.Where(productID => productID == x.ID).Count() }));
                var rowsEffected = ShopServices.Instance.SaveOrder(neworder);

                result.Data = new { Success = true };
            }
            else
            {
                result.Data = new { Success = false };

            }
            return result;
        }


        [Authorize]
        public ActionResult UserOrders(string userID, string status, int? pageNo)
        {
            UserOrdersViewModel model = new UserOrdersViewModel();
            model.UserID = userID;
            model.Status = status;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var pageSize = ConfigurationServices.Instance.CategoryPageSize();

            model.Order = OrderServices.Instance.SearchOrders(userID, status, pageNo.Value, pageSize);
            var totalRecord = OrderServices.Instance.SearchOrderscount(userID, status);
            model.Pager = new Pager(totalRecord, pageNo, pageSize);

            return View(model);
        }

        public ActionResult DetailsUserOrder(int ID)
        {
            OrderDetailViewModel model = new OrderDetailViewModel();
            model.Order = OrderServices.Instance.GetOrderbyID(ID);
            if (model.Order != null)
            {
                model.Orderby = UserManager.FindById(model.Order.UserID);
            }
            model.AvailableStatuses = new List<string>() { "Pending", "In Progress", "Delivered" };

            return View(model);
        }
    }
}

Book_Shop.web/Views/Shop/Index.cshtml
@using Book_Shop.web.Code
@model ShopViewModel
@{
    ViewBag.Title = "Index";
}



<section class="flat-row main-shop shop-slidebar" style="background-color: #ffffff">
    @*<div class="container" >*@
        <div class="row">
            <div class="col-sm-3 text-lg-left"  style="background-color: #ffffff; margin-top:0px; padding: 0px;">
                <div class="sidebar slidebar-shop">

                @*<div class="Searchbody">
                        <form role="search" method="get" class="search-form" action="@Url.Action("Index", "shop")">
                    <div class="Searchbox">
                            <input class="Searchtxt" type="text"  placeholder="Search" value="@Model.searchTerm" name="searchTerm">*@
                            @*<input  type="submit" style="">*@
                                @*<input type="submit" class="Searchbtn fas fa-search" value="">
                           

                    </div>
                        </form>
                </div>*@




                    <div class="widget widget-search">
                        <form role="search" method="get" class="search-form" action="@Url.Action("Index", "shop")">
                            <label>
                                <input type="search" class="search-field" placeholder="Search by Name" value="@Model.searchTerm" name="searchTerm" style="padding-left:10px;">
                            </label>
                            <input type="submit" class="search-submit" value="Search">
                        </form>
                    </div><!-- /.widget-search -->

                    <div class="widget widget_tag">
                        <h5 class="widget-title">
                            Feature Categories
                        </h5>
                        <div class="tag-list" style="width:112%">
                            @foreach (var category in Model.FeaturedCategories)
                            {
                                <ul>
                                    <li> <a data-href="@Url.Action("FilterProducts", "shop", new { categoryID = category.ID, sortby = Model.sortby})" class="datalink @(Model.categoryID.HasValue && Model.categoryID.Value == category.ID ? "active" : string.Empty)">@category.Name</a></li>
                                </ul>
                            }

                        </div>
                    <hr />
                        <div class="widget widget-price">
                            <h5 class="widget-title">Filter by price</h5>
                            <div class="price-filter">
                                <div id="slide-range"></div>
                                <p class="amount">
                                    Price: <input type="text" id="amount" disabled="">
                                </p>
                            </div>
                        </div>
                    </div><!-- /.widget -->

                    <div class="widget widget_tag widget-sort-by">
                        <h5 class="widget-title">
                            SORT BY
                        </h5>
                        <ul>
                            <li><a data-href="@Url.Action("FilterProducts", "shop", new { Sortby = (int)SortbyEnum.Default,         categoryID = Model.categoryID })" class="datalink @(Model.sortby.HasValue ? Model.sortby.Value == (int)SortbyEnum.Default ? "active" : string.Empty : string.Empty)" style="font-size:20px;">Default</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "shop", new { Sortby = (int)SortbyEnum.Popularity,      categoryID = Model.categoryID })" class="datalink @(Model.sortby.HasValue ? Model.sortby.Value == (int)SortbyEnum.Popularity ? "active" : string.Empty : string.Empty)" style="font-size:20px;">Popularity</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "shop", new { Sortby = (int)SortbyEnum.Pricelowtohigh,  categoryID = Model.categoryID })" class="datalink @(Model.sortby.HasValue ? Model.sortby.Value == (int)SortbyEnum.Pricelowtohigh ? "active" : string.Empty : string.Empty)" style="font-size:20px;">Price: low to high</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "shop", new { Sortby = (int)SortbyEnum.Pricehightolow,  categoryID = Model.categoryID })" class="datalink @(Model.sortby.HasValue ? Model.sortby.Value == (int)SortbyEnum.Pricehightolow ? "active" : string.Empty : string.Empty)" style="font-size:20px;">Price: high to low</a></li>
                        </ul>
                    </div><!-- /.widget-sort-by -->

                   
                    <a class="btn" href="@Url.Action("index","shop") ">Reset</a>
                </div><!-- /.sidebar -->
            </div><!-- /.col-md-3 -->
            <div class="col-md-9">
                <div id="ProductDiv">
                    @{
                        var filterProductViewModel = new FilterProductsViewModel();
                        filterProductViewModel.Products = Model.Products;
                        filterProductViewModel.pager = Model.pager;
                        filterProductViewModel.categoryID = Model.categoryID;
                        filterProductViewModel.sortby = Model.sortby;

                        Html.RenderPartial("FilterProducts", filterProductViewModel);
                    }
                </div>


            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    @*</div>*@<!-- /.container -->
</section><!-- /.flat-row -->

<script>
    var callTimeout;
    var priceSlider = $( "#slide-range" ).slider({
          range: true,
          min: 0,
          max: @Model.MaximamPrice,
          values: [0, @Model.MaximamPrice ],
          slide: function (event, ui) {
              var minPrice = ui.values[0];
              var maxPrice = ui.values[1];

              $("#amount").val("Rs" + minPrice + ".00" + " - " + "Rs" + maxPrice + ".00");
              clearTimeout(callTimeout);
              callTimeout = setTimeout(PriceRangeChange, 500);
        }
    });

    $(".datalink").click(function () {

        var url = $(this).attr("data-href");

        if (url != "" || url != undefined) {
            GetData(url);
        }
    })

    function GetData(dUrl) {
      
         $.ajax({
             url: dUrl,
             data: {
                 sortby: $("#SortBy").val(),
                 categoryID: $("#CategoryID").val(),
                 minimumPrice: priceSlider.slider("values", 0),
                 maximaumPrice: priceSlider.slider("values", 1)
             }
        })
             .done(function (response) {
                 $("#ProductDiv").html(response);
           })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });
    }

    function PriceRangeChange() {
        debugger;
         $.ajax({
             url: '@Url.Action("filterProducts", "Shop")',
             data: {
                 searchTerm: $("#SearchTerm").val(),
                 sortby: $("#SortBy").val(),
                 categoryID: $("#CategoryID").val(),
                 minimumPrice: priceSlider.slider("values", 0),
                 maximaumPrice: priceSlider.slider("values", 1)
             }
        })
             .done(function (response) {
                 $("#ProductDiv").html(response);
           })
             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });
       }
</script>

Book_Shop.web/Views/Shop/UserOrders.cshtml
@model UserOrdersViewModel

@{
    ViewBag.Title = "UserOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="title-section">
            <h2 class="title">User Order</h2>
        </div>
    </div>
</div>

<div class="container">
    <div id="tablecontainer">
        @*<div>
                <form method="post">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label>Search</label>
                                <input class="form-control" id="searchtxt" name="UserID" value="@Model.UserID" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Action</label>
                                <div class="row">
                                    <div class="col-md-4 pr-0">
                                        <button class="form-control btn btn-primary" type="submit" id="searchBtn">Search</button>
                                    </div>
                                    <div class="col-md-4 pr-0">
                                        <a class="form-control btn btn-primary" type="button" href="@Url.Action("Index","Order", new {pageNo = 1 })" id="resetBtn">Reset</a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>*@

        <div>

            <table class="table table-striped" id="table">
                <thead>
                    <tr>
                        <th class="font-weight-bold">User ID</th>
                        <th class="font-weight-bold">Total Price</th>
                        <th class="font-weight-bold">Status</th>
                        <th class="font-weight-bold ">Action</th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model.Order != null && Model.Order.Count > 0)
                    {
                        if (User.Identity.IsAuthenticated)
                        {
                            foreach (var order in Model.Order)
                            {
                                <tr>
                                    <td>@order.UserID</td>
                                    <td>
                                        @order.TotalAmount
                                    </td>
                                    <td>@order.Status</td>
                                    <td>
                                        <a class="detailbtn"  href="@Url.Action("DetailsUserOrder", "Shop", new { ID = order.ID })">Detail</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td class="text-danger" colspan="4">No Order found</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div style="text-align:center; font-size:20px;">

                @if (Model.Pager != null && Model.Pager.TotalPages > 1)
                {
                    if (Model.Pager.CurrentPage > 1)
                    {
                        <a class="pageButtons" data-pageno="1" href="@Url.Action("Userorders","shop", new { userID = Model.UserID, status = Model.Status, pageNo = 1 })"><i  class="fas fa-angle-double-left"  style="background-color:#0b9ea3; color:white; transform: scale(1.5,1.5);"></i></a>
                        <span style="color:white;">-</span>
                        <a class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)" href="@Url.Action("Userorders","shop", new { userID = Model.UserID, status = Model.Status, pageNo = Model.Pager.CurrentPage - 1 })"><i class="fa fa-angle-left" style="background-color:#0b9ea3; color:white; transform: scale(2,1.5);"></i></a>
                    }
                    <span style="color:white;">-</span>

                    for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                    {
                        var activeclass = Model.Pager.CurrentPage == page ? "Active bg-info" : string.Empty;
                        <a class="@activeclass pageButtons" data-pageno="@page" href="@Url.Action("Userorders","shop", new { userID = Model.UserID, status = Model.Status, pageNo = page})">@page</a>

                    }

                    <span style="color:white;">-</span>
                    if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                    {
                        <a class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)" href="@Url.Action("Userorders","shop", new { userID = Model.UserID, status = Model.Status, pageNo = Model.Pager.CurrentPage + 1 })"><i class="fa fa-angle-right" style="background-color:#0b9ea3; color:white; transform: scale(2,1.5);"></i></a>
                        <span style="color:white;">-</span>
                        <a class="pageButtons" data-pageno="@Model.Pager.EndPage" href="@Url.Action("Userorders","shop", new { userID = Model.UserID, status = Model.Status, pageNo = Model.Pager.EndPage })"><i  class="fas fa-angle-double-right" style="background-color:#0b9ea3; color:white; transform: scale(1.5,1.5);"></i></a>
                    }
                }
            </div>
        </div>
    </div>
</div>

<script>
    function focusAction(controltofocus) {
        $("html, body").animate({
            scrollTop: $("#" + controltofocus).offset().top - 100
        }, 1000);
    }

     @*$(".deletebtn").click(function () {
        var confirmdelete = confirm("Are you sure to delete this Record !!");
        if (confirmdelete) {

            $.ajax({
            //type:"post",
            url: '@Url.Action("DeleteOrder", "order")',
            data: {
                ID: $(this).attr("data-id")
            }
        })
            .done(function (response) {
                $("#table").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });

        }
     });*@

</script>