Book_Shop.web/Controllers/ContactController.cs
using Book_Shop.database;
using Book_Shop.Entities;
using Book_Shop.Services;
using Book_Shop.web.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Book_Shop.web.Controllers
{
    public class ContactController : Controller
    {

        // GET: Contact
        public ActionResult Index()
        {
           
                return View();
            
        }

        public ActionResult ContactTable(string userID /*string search, int? pageNo*/)
        {
           using(var context = new CBContext())
            {
                return PartialView(context.Contacts.ToList());
            }
            
        }



        public ActionResult Create()
        {
            return View(new Contact());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Contact model)
        {
            using (var context = new CBContext())
            {
                if (ModelState.IsValid)
                {
                    context.Contacts.Add(model);
                    await context.SaveChangesAsync();
                    return RedirectToAction("Index","home");
                }
                return View(model);
            }
        }




        //public ActionResult Profile()
        //{
        //    return View(new Contact());
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Profile(Contact model)
        //{
        //    using (var context = new CBContext())
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            context.Contacts.Add(model);
        //            await context.SaveChangesAsync();//Save data to sql database
        //            return RedirectToAction("Index");
        //        }
        //        return View(model);
        //    }
        //}

        //public ActionResult Edit(int ID)
        //{
        //    var contact = ContactServices.Instance.GetContact(ID);
        //    return PartialView(contact);
        //}
        //[HttpPost]
        //public ActionResult Edit(Contact contact)
        //{
        //    ContactServices.Instance.UpdateContact(contact);
        //    return RedirectToAction("ContactTable");
        //}

        public ActionResult Details(int ID)
        {
            Contact model = new Contact();

            model = ContactServices.Instance.GetContactbyID(ID);

            return View(model);

        }
      
        public ActionResult Delete(int ID)
        {
            ContactServices.Instance.DeleteContact(ID);
            return RedirectToAction("index");
        }


    }
}

Book_Shop.web/Views/Contact/ContactTable.cshtml
@model  IEnumerable<Book_Shop.Entities.Contact>
@{
    ViewBag.Title = "Index";
  
}

<link href="~/Content/css1/style.css" rel="stylesheet" />


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |*@
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
           
        </tr>
    }
</table>

Book_Shop.web/Views/Contact/Create.cshtml
@model Book_Shop.Entities.Contact

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <!DOCTYPE html>
    <html>
    <head>
        <title>Client Contact Form Flat Responsive Widget Template :: w3layouts</title>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="Client Contact Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!-- Custom Theme files -->
        @*<link href="/clientcontact/css/style.css" rel="stylesheet" type="text/css" media="all" />*@
        <link href="~/Content/css1/style.css" rel="stylesheet" />

        <!-- //Custom Theme files -->
        <!-- web font -->
        <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
        <link href="//fonts.googleapis.com/css?family=Amita:400,700" rel="stylesheet">
        <!-- //web font -->
    </head>
    <body>


        <div class="page-title parallax parallax1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title-section margin-bottom-52">
                <h2 class="title">
                    CONTACT US
                </h2>
            </div><!-- /.page-title-heading -->
                        <div class="breadcrumbs">
                            <ul>
                                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </div><!-- /.breadcrumbs -->
                    </div><!-- /.col-md-12 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- /.page-title -->

        <section class="flat-row flat-iconbox">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title-section">
                            <h2 class="title">
                                Get In Touch
                            </h2>
                        </div><!-- /.title-section -->
                    </div><!-- /.col-md-12 -->
                </div><!-- /.row -->
                <div class="row">
                    <div class="col-md-4">
                        <div class="iconbox text-center">
                            <div class="box-header nomargin">
                                <div class="icon">
                                     <i class="fa fa-map-marker"></i>
                                </div>
                            </div><!-- /.box-header -->
                            <div class="box-content">
                                <p>Chatta Bahtawar, Islamabad</p>
                            </div><!-- /.box-content -->
                        </div><!-- /.iconbox -->
                    </div><!-- /.col-md-4 -->
                    <div class="col-md-4">
                        <div class="divider h0"></div>
                        <div class="iconbox text-center">
                            <div class="box-header">
                                <div class="icon">       
                                    <i class="fa fa-phone"></i>
                                </div>
                            </div><!-- /.box-header -->
                            <div class="box-content">
                                <p>+92 3341938473 / +92 3171906299</p>
                            </div><!-- /.box-content -->
                        </div><!-- /.iconbox -->
                    </div><!-- /.col-md-4 -->
                    <div class="col-md-4">
                        <div class="divider h0"></div>
                        <div class="iconbox text-center">
                            <div class="box-header">
                                <div class="icon">
                                    <i class="fa fa-envelope"></i>
                                </div>
                            </div><!-- /.box-header -->
                            <div class="box-content">
                                <p>Info@bookshop.com</p>
                            </div><!-- /.box-content -->
                        </div><!-- /.iconbox -->
                    </div><!-- /.col-md-4 -->
                </div><!-- /.row -->
                <div class="divider h43"></div>
                <div class="row">
                    <div class="col-md-12" >
                        @*<div class="flat-map"></div>*@
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3320.9970993562256!2d73.15438931454379!3d33.65723704589099!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dfea49ba502323%3A0x4cc1def45a08aa35!2sCapital%20View%20Boys%20Hostel!5e0!3m2!1sen!2s!4v1581071537915!5m2!1sen!2s" width="1200" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                    </div><!-- /.col-md-12 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </section><!-- /.flat-row -->


        <section class="flat-row flat-contact">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title-section margin_bottom_17">
                            <h2 class="title">
                                Send Us Email
                            </h2>
                        </div><!-- /.title-section -->
                    </div><!-- /.col-md-12 -->
                </div><!-- /.row -->

            <br /><br />
                <div class="row">
                    <div class="wrap-contact style2">

@using (Html.BeginForm("Create", "Contact", FormMethod.Post))
{
    @Html.AntiForgeryToken()
                      
                            <div class="form-text-wrap clearfix">
                                <div class="contact-name">
                                    @Html.TextBoxFor(m => m.FullName, new { @placeholder = "Full name" })
                                    @Html.ValidationMessageFor(m => m.FullName)
                                </div>
                                <div class="contact-subject">
                                    @Html.TextBoxFor(m => m.Email, new { @placeholder = "Email" })
                                    @Html.ValidationMessageFor(m => m.Email)
                                </div>
                                <div class="contact-name">
                                    @Html.TextBoxFor(m => m.PhoneNumber, new { @placeholder = "Mobile Number" })
                                    @Html.ValidationMessageFor(m => m.PhoneNumber)
                                </div>
                               
                            </div>
                            <br /><br />
                            <div class="contact-message clearfix">
                                @Html.TextAreaFor(m => m.Message, new { @placeholder = "Message", @Style= "background-color:white;" })
                                @Html.ValidationMessageFor(m => m.Message)
                            </div>
                            <div class="form-submit">
                                <input type="submit" value="SUBMIT" class="btn">
                            </div>
}
                    </div><!-- /.wrap-contact -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </section><!-- /.flat-row -->



    </body>
</html>

Book_Shop.web/Views/Contact/Details.cshtml
@model Book_Shop.Entities.Contact

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.TextAreaFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

Book_Shop.web/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";


}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">



<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="title-section">
                <h2 class="title" style="font-size:40px; text-align:center; color:#126c81">Contact</h2>
            </div>
        </div>
    </div>
    <div id="tablecontainer">
        @{
            Html.RenderAction("ContactTable");
        }
    </div>
    <hr />
</div>

Book_Shop.web/Views/Contact/Profile.cshtml
@*@model Book_Shop.Entities.Contact


@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/css1/style.css" rel="stylesheet" />

<!DOCTYPE html>
<html>
<head>
    <title>Profile Contact Form Flat Responsive Widget Template :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Profile Contact Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="/profile/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main">
        <h1>Profile Contact Form</h1>
        <div class="main-wthree-row">
            <h4><span>Lorem ipsum </span>dolor Sit amet consec tetur adip iscing elit.</h4>
            <div class="agileits-info">
                <div class="agileits-infoleft">

                    <img src="~/Content/images1/img1.jpg" />
                    <div class="agileits-infotext">
                        <h2>Jose Leiter</h2>
                        <h6>Fashion Designer</h6>
                    </div>
                </div>
                <div class="agileits-inforight">
                    <p><img src="~/Content/images1/i1.png" /> +01 11 222 3333</p>
                    <p><img src="~/Content/images1/i2.png" /><a href="mailto:example@mail.com"> mail@example.com</a></p>
                </div>
                <div class="clear"> </div>
            </div>
            <h3>Send a message to me</h3>
            <div class="contact-wthree">
                @using (Html.BeginForm("Profile", "Contact", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="contact-w3left w3-agile">
                        @Html.TextBoxFor(m => m.FullName, new { @placeholder = "Full Name" })
                        @Html.TextBoxFor(m => m.PhoneNumber, new { @placeholder = "Mobile Number", @class = "email" })
                        @Html.TextBoxFor(m => m.Email, new { @placeholder = "Email" })
                    </div>
                    <div class="contact-w3right">
                        @Html.TextAreaFor(m => m.Message, new { @placeholder = "Message" })
                        <input type="submit" value="SUBMIT">
                    </div>
                    <div class="clear"> </div>
                }
            </div>
        </div>
    </div>
    <!-- //main -->
    <!-- copyright -->
    <div class="w3copyright-agile">
        <p>© 2017 Profile Contact Form. All rights reserved | Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a></p>
    </div>
    <!-- //copyright -->
</body>
</html>*@